name: Sync to Azure DevOps

on:
  push:
    branches:
      - master  

jobs:
  sync-to-azure:
    runs-on: windows-latest
    environment: envi  
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
      
    - name: Add and Push to Azure DevOps Remote
      run: |
        # Add the Azure DevOps remote using username and PAT
        git remote add azure https://${{ secrets.AZURE_DEVOPS_USERNAME }}:${{ secrets.AZURE_DEVOPS_PASSWORD }}@dev.azure.com/vladutgi/incercare1/_git/licenta.git
        
        # Verify the remote URL
        git remote -v
        
        # Push to Azure DevOps master branch
        git push azure master
