name: Sync to Azure DevOps

on:
  push:
    branches:
      - master  

jobs:
  sync-to-azure:
    runs-on: windows-latest
    environment: envi  
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
      
    - name: Push changes to Azure DevOps
      env:
        AZURE_DEVOPS_USERNAME: ${{ secrets.AZURE_DEVOPS_USERNAME }}
        AZURE_DEVOPS_PASSWORD: ${{ secrets.AZURE_DEVOPS_PASSWORD }}
      run: |
        # Add the Azure DevOps remote using username and PAT for authentication
        git remote add azure https://$AZURE_DEVOPS_USERNAME:${{ secrets.AZURE_DEVOPS_PASSWORD }}@dev.azure.com/vladutgi/incercare1/_git/licenta.git
        git push azure master  
