name: Sync to Azure DevOps

on:
  push:
    branches:
      - master  

jobs:
  sync-to-azure:
    runs-on: windows-latest
    environment: envi  
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
      
    - name: Add Azure DevOps Remote
      run: |
        git remote add azure https://${{ secrets.AZURE_DEVOPS_USERNAME }}:${{ secrets.AZURE_DEVOPS_PASSWORD }}@dev.azure.com/vladutgi/incercare1/_git/licenta.git

    - name: Pull Remote Changes
      run: |
        # Fetch and merge changes from Azure DevOps
        git pull --rebase azure master

    - name: Push to Azure DevOps
      run: |
        # Push the changes to Azure DevOps master branch
        git push azure master
